import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import MainLayout from "@/components/layouts/main-layout"

const poppinsSans = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <title>Given Frozen Food</title>
      </head>
      {/* <body className={`${poppinsSans.className} antialiased dark:bg-gray-900 dark:text-white`}> */}
      <body className={`${poppinsSans.className} antialiased`}>
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  )
}
